# Generated by Django 5.2.11 on 2026-04-18 13:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_review', '0003_add_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_case_statuses', models.JSONField(blank=True, default=list, help_text="List of TestCaseStatus.name values allowed for review. Leave empty to fall back to REVIEW_ALLOWED_CASE_STATUSES (default: ['PROPOSED']).")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review plugin configuration',
                'verbose_name_plural': 'Review plugin configuration',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReviewStatusTransition',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source_status', models.CharField(help_text='TestCaseStatus.name that triggers the transition.', max_length=100)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('needs_changes', 'Needs changes'), ('rejected', 'Rejected')], max_length=32)),
                ('target_status', models.CharField(help_text='TestCaseStatus.name to transition to.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Review status transition',
                'verbose_name_plural': 'historical Review status transitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReviewStatusTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_status', models.CharField(help_text='TestCaseStatus.name that triggers the transition.', max_length=100)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('needs_changes', 'Needs changes'), ('rejected', 'Rejected')], max_length=32)),
                ('target_status', models.CharField(help_text='TestCaseStatus.name to transition to.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review status transition',
                'verbose_name_plural': 'Review status transitions',
                'ordering': ['source_status', 'decision'],
                'unique_together': {('source_status', 'decision')},
            },
        ),
    ]
