# Generated by Django 5.2.11 on 2026-04-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_review', '0006_resubmit_transitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreviewstatustransition',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('needs_changes', 'Needs changes'), ('rejected', 'Rejected'), ('pending', 'Pending (resubmit)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reviewstatustransition',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('needs_changes', 'Needs changes'), ('rejected', 'Rejected'), ('pending', 'Pending (resubmit)')], max_length=32),
        ),
    ]
