# Generated by Django 5.2.11 on 2026-04-19 07:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcms_review', '0007_allow_pending_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiIntegrationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('disabled', 'Disabled'), ('outline', 'Outline'), ('confluence', 'Confluence')], default='disabled', help_text="Which wiki to sync reviews to. 'Disabled' skips sync entirely.", max_length=16)),
                ('base_url', models.URLField(blank=True, help_text='Wiki base URL, e.g. https://outline.example.com or https://example.atlassian.net/wiki')),
                ('api_token', models.CharField(blank=True, help_text="API token (Outline: 'ol_api_...'; Confluence: an atlassian.com API token paired with the email below).", max_length=255)),
                ('auth_email', models.EmailField(blank=True, help_text='Confluence only — the email address that owns the API token.', max_length=254)),
                ('collection_id', models.CharField(blank=True, help_text='Outline collection UUID or Confluence space key where review pages are created.', max_length=128)),
                ('auto_create', models.BooleanField(default=True, help_text='Create a wiki page when a ReviewRequest is first saved.')),
                ('auto_update', models.BooleanField(default=True, help_text='Append a changelog entry on every state change.')),
                ('auto_close_marker', models.BooleanField(default=True, help_text="Mark the page as 'Approved' / 'Closed' when the review reaches a terminal state.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wiki integration configuration',
                'verbose_name_plural': 'Wiki integration configuration',
            },
        ),
        migrations.AddField(
            model_name='historicalreviewrequest',
            name='wiki_page_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='wiki_page_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='HistoricalWikiIntegrationConfig',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('backend', models.CharField(choices=[('disabled', 'Disabled'), ('outline', 'Outline'), ('confluence', 'Confluence')], default='disabled', help_text="Which wiki to sync reviews to. 'Disabled' skips sync entirely.", max_length=16)),
                ('base_url', models.URLField(blank=True, help_text='Wiki base URL, e.g. https://outline.example.com or https://example.atlassian.net/wiki')),
                ('auth_email', models.EmailField(blank=True, help_text='Confluence only — the email address that owns the API token.', max_length=254)),
                ('collection_id', models.CharField(blank=True, help_text='Outline collection UUID or Confluence space key where review pages are created.', max_length=128)),
                ('auto_create', models.BooleanField(default=True, help_text='Create a wiki page when a ReviewRequest is first saved.')),
                ('auto_update', models.BooleanField(default=True, help_text='Append a changelog entry on every state change.')),
                ('auto_close_marker', models.BooleanField(default=True, help_text="Mark the page as 'Approved' / 'Closed' when the review reaches a terminal state.")),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Wiki integration configuration',
                'verbose_name_plural': 'historical Wiki integration configuration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
