"""DOCX renderer for review reports.

Takes the plain dicts produced by tcms_review.exports.data.* and writes
them into a Microsoft Word document via python-docx. No dependency on
Django templating — the document is a direct Office Open XML doc.
"""
from io import BytesIO


def _fmt_dt(value):
    if value is None:
        return "—"
    return value.strftime("%Y-%m-%d %H:%M")


def _fmt_td(td):
    if td is None:
        return "—"
    total_ms = int(td.total_seconds() * 1000)
    if total_ms < 0:
        total_ms = 0
    hours, rem_ms = divmod(total_ms, 3_600_000)
    minutes, rem_ms = divmod(rem_ms, 60_000)
    seconds, ms = divmod(rem_ms, 1000)
    return f"{hours:02d}h {minutes:02d}m {seconds:02d}s {ms:03d}ms"


def _styled_heading(doc, text, level=1):
    heading = doc.add_heading(text, level=level)
    return heading


def _kv_table(doc, rows):
    from docx.shared import Inches  # noqa: WPS433
    table = doc.add_table(rows=len(rows), cols=2)
    table.style = "Light List Accent 1"
    table.columns[0].width = Inches(2.0)
    for i, (k, v) in enumerate(rows):
        table.rows[i].cells[0].text = k
        table.rows[i].cells[1].text = str(v) if v is not None else "—"
    return table


def _render_review_block(doc, review, items, votes, metrics=None):
    """Render one review (single or consolidated entry) into doc."""
    _styled_heading(doc, f"Review #{review['id']} — {review['title']}", level=2)

    _kv_table(doc, [
        ("State", review["state_display"]),
        ("Requester", review["requester"]),
        ("Reviewers", ", ".join(review.get("reviewers", [])) or "—"),
        ("Created", _fmt_dt(review["created_at"])),
        ("Due date", _fmt_dt(review.get("due_date"))),
        ("Last updated", _fmt_dt(review.get("updated_at"))),
    ])

    if review.get("description"):
        doc.add_paragraph()
        p = doc.add_paragraph()
        p.add_run("Description").bold = True
        doc.add_paragraph(review["description"])

    if metrics:
        doc.add_paragraph()
        p = doc.add_paragraph()
        p.add_run("Metrics").bold = True
        votes_breakdown = metrics.get("votes", {})
        _kv_table(doc, [
            ("Approvals", votes_breakdown.get("approved", 0)),
            ("Rejections", votes_breakdown.get("rejected", 0)),
            ("Changes requested", votes_breakdown.get("needs_changes", 0)),
            ("Participation", f"{int(metrics.get('participation', 0) * 100)}%"),
            ("Time to decision", _fmt_td(metrics.get("time_to_decision"))),
        ])

    # Cases table
    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run(f"Cases under review ({len(items)})").bold = True
    if items:
        table = doc.add_table(rows=1 + len(items), cols=4)
        table.style = "Light Grid Accent 1"
        headers = table.rows[0].cells
        headers[0].text = "#"
        headers[1].text = "Summary"
        headers[2].text = "Decision"
        headers[3].text = "Comment"
        for i, it in enumerate(items, 1):
            row = table.rows[i].cells
            row[0].text = str(it["case_id"])
            row[1].text = it["summary"]
            row[2].text = it["decision_display"]
            row[3].text = it.get("comment") or "—"
    else:
        doc.add_paragraph("No cases attached.").italic = True

    # Votes table
    doc.add_paragraph()
    p = doc.add_paragraph()
    p.add_run(f"Votes ({len(votes)})").bold = True
    if votes:
        table = doc.add_table(rows=1 + len(votes), cols=4)
        table.style = "Light Grid Accent 1"
        headers = table.rows[0].cells
        headers[0].text = "Reviewer"
        headers[1].text = "Decision"
        headers[2].text = "Comment"
        headers[3].text = "Voted at"
        for i, v in enumerate(votes, 1):
            row = table.rows[i].cells
            row[0].text = v["reviewer"]
            row[1].text = v["decision_display"]
            row[2].text = v.get("comment") or "—"
            row[3].text = _fmt_dt(v["voted_at"])
    else:
        doc.add_paragraph("No votes cast yet.").italic = True


def _footer(doc, generated_at):
    doc.add_paragraph()
    doc.add_paragraph(
        f"Generated by kiwitcms-review at {_fmt_dt(generated_at)}"
    ).italic = True


def render_single_review(data):
    from docx import Document  # noqa: WPS433

    doc = Document()
    _styled_heading(doc, f"Review Request #{data['review']['id']}", level=0)
    doc.add_paragraph(data["review"]["title"]).italic = True
    doc.add_paragraph()
    _render_review_block(
        doc,
        data["review"],
        data["items"],
        data["votes"],
        metrics=data.get("metrics"),
    )
    _footer(doc, data["generated_at"])

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


def render_consolidated(data):
    """Consolidated report: summary + one block per review."""
    from docx import Document  # noqa: WPS433

    doc = Document()
    _styled_heading(doc, data["title"], level=0)

    date_range = data.get("date_range") or {}
    if date_range.get("start") or date_range.get("end"):
        doc.add_paragraph(
            f"Date range: {_fmt_dt(date_range.get('start'))} — "
            f"{_fmt_dt(date_range.get('end'))}"
        ).italic = True

    summary = data.get("summary", {})
    doc.add_paragraph()
    _styled_heading(doc, "Summary", level=1)
    rows = [
        ("Total reviews", summary.get("total_reviews", 0)),
        ("Total cases in scope", summary.get("total_cases", 0)),
    ]
    for state_label, count in (summary.get("by_state") or {}).items():
        rows.append((f"State — {state_label}", count))
    _kv_table(doc, rows)

    doc.add_page_break()
    _styled_heading(doc, "Reviews", level=1)

    reviews = data.get("reviews", [])
    if not reviews:
        doc.add_paragraph("No review requests matched this scope.").italic = True
    else:
        for review in reviews:
            _render_review_block(
                doc,
                review,
                review.get("items", []),
                review.get("votes", []),
            )
            doc.add_page_break()

    _footer(doc, data["generated_at"])

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
